import { test, expect } from "@playwright/test";

test("robots.txt allows crawl and points to sitemap-index", async ({ request }) => {
  const res = await request.get("/robots.txt");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toMatch(/User-agent:\s*\*/);
  expect(body).toMatch(/Allow:\s*\//);
  expect(body).toMatch(/Sitemap:\s*https:\/\/wavival\.dev\/sitemap-index\.xml/);
});

test("sitemap-index.xml is generated by @astrojs/sitemap", async ({ request }) => {
  const res = await request.get("/sitemap-index.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("<sitemapindex");
  expect(body).toContain("https://wavival.dev/sitemap-0.xml");
});
